/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Lang } from "./utils/data";
export { Lang } from "./utils/data";
export namespace Components {
    interface AppPortfolio {
    }
    interface IntroButton {
        "onSetchangetext": () => void;
        "playButtonRef"?: (el: HTMLDivElement) => void;
    }
    interface MyTaypage {
    }
    interface PortfolioCmdk {
        /**
          * @default 'pt'
         */
        "locale": Lang;
        /**
          * @default false
         */
        "open": boolean;
    }
    interface PortfolioCommunication {
        /**
          * @default 'pt'
         */
        "locale": Lang;
    }
    interface PortfolioContact {
        /**
          * @default 'pt'
         */
        "locale": Lang;
    }
    interface PortfolioHero {
        /**
          * @default 'pt'
         */
        "locale": Lang;
    }
    interface PortfolioLedgb {
        /**
          * @default 'pt'
         */
        "locale": Lang;
    }
    interface PortfolioManifesto {
        /**
          * @default 'pt'
         */
        "locale": Lang;
    }
    interface PortfolioProjects {
        /**
          * @default 'pt'
         */
        "locale": Lang;
    }
    interface PortfolioSectHead {
        /**
          * @default ''
         */
        "num": string;
        /**
          * @default ''
         */
        "sub": string;
        /**
          * @default ''
         */
        "titleHtml": string;
    }
    interface PortfolioStack {
        /**
          * @default 'pt'
         */
        "locale": Lang;
    }
    interface PortfolioTerminal {
    }
    interface PortfolioTopbar {
        /**
          * @default 'pt'
         */
        "locale": Lang;
    }
    interface PortfolioTrajectory {
        /**
          * @default 'pt'
         */
        "locale": Lang;
    }
}
export interface PortfolioCmdkCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPortfolioCmdkElement;
}
export interface PortfolioContactCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPortfolioContactElement;
}
export interface PortfolioTopbarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPortfolioTopbarElement;
}
declare global {
    interface HTMLAppPortfolioElement extends Components.AppPortfolio, HTMLStencilElement {
    }
    var HTMLAppPortfolioElement: {
        prototype: HTMLAppPortfolioElement;
        new (): HTMLAppPortfolioElement;
    };
    interface HTMLIntroButtonElement extends Components.IntroButton, HTMLStencilElement {
    }
    var HTMLIntroButtonElement: {
        prototype: HTMLIntroButtonElement;
        new (): HTMLIntroButtonElement;
    };
    interface HTMLMyTaypageElement extends Components.MyTaypage, HTMLStencilElement {
    }
    var HTMLMyTaypageElement: {
        prototype: HTMLMyTaypageElement;
        new (): HTMLMyTaypageElement;
    };
    interface HTMLPortfolioCmdkElementEventMap {
        "cmdClose": void;
        "cmdAction": { action: string };
    }
    interface HTMLPortfolioCmdkElement extends Components.PortfolioCmdk, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPortfolioCmdkElementEventMap>(type: K, listener: (this: HTMLPortfolioCmdkElement, ev: PortfolioCmdkCustomEvent<HTMLPortfolioCmdkElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPortfolioCmdkElementEventMap>(type: K, listener: (this: HTMLPortfolioCmdkElement, ev: PortfolioCmdkCustomEvent<HTMLPortfolioCmdkElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPortfolioCmdkElement: {
        prototype: HTMLPortfolioCmdkElement;
        new (): HTMLPortfolioCmdkElement;
    };
    interface HTMLPortfolioCommunicationElement extends Components.PortfolioCommunication, HTMLStencilElement {
    }
    var HTMLPortfolioCommunicationElement: {
        prototype: HTMLPortfolioCommunicationElement;
        new (): HTMLPortfolioCommunicationElement;
    };
    interface HTMLPortfolioContactElementEventMap {
        "copyEmail": void;
    }
    interface HTMLPortfolioContactElement extends Components.PortfolioContact, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPortfolioContactElementEventMap>(type: K, listener: (this: HTMLPortfolioContactElement, ev: PortfolioContactCustomEvent<HTMLPortfolioContactElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPortfolioContactElementEventMap>(type: K, listener: (this: HTMLPortfolioContactElement, ev: PortfolioContactCustomEvent<HTMLPortfolioContactElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPortfolioContactElement: {
        prototype: HTMLPortfolioContactElement;
        new (): HTMLPortfolioContactElement;
    };
    interface HTMLPortfolioHeroElement extends Components.PortfolioHero, HTMLStencilElement {
    }
    var HTMLPortfolioHeroElement: {
        prototype: HTMLPortfolioHeroElement;
        new (): HTMLPortfolioHeroElement;
    };
    interface HTMLPortfolioLedgbElement extends Components.PortfolioLedgb, HTMLStencilElement {
    }
    var HTMLPortfolioLedgbElement: {
        prototype: HTMLPortfolioLedgbElement;
        new (): HTMLPortfolioLedgbElement;
    };
    interface HTMLPortfolioManifestoElement extends Components.PortfolioManifesto, HTMLStencilElement {
    }
    var HTMLPortfolioManifestoElement: {
        prototype: HTMLPortfolioManifestoElement;
        new (): HTMLPortfolioManifestoElement;
    };
    interface HTMLPortfolioProjectsElement extends Components.PortfolioProjects, HTMLStencilElement {
    }
    var HTMLPortfolioProjectsElement: {
        prototype: HTMLPortfolioProjectsElement;
        new (): HTMLPortfolioProjectsElement;
    };
    interface HTMLPortfolioSectHeadElement extends Components.PortfolioSectHead, HTMLStencilElement {
    }
    var HTMLPortfolioSectHeadElement: {
        prototype: HTMLPortfolioSectHeadElement;
        new (): HTMLPortfolioSectHeadElement;
    };
    interface HTMLPortfolioStackElement extends Components.PortfolioStack, HTMLStencilElement {
    }
    var HTMLPortfolioStackElement: {
        prototype: HTMLPortfolioStackElement;
        new (): HTMLPortfolioStackElement;
    };
    interface HTMLPortfolioTerminalElement extends Components.PortfolioTerminal, HTMLStencilElement {
    }
    var HTMLPortfolioTerminalElement: {
        prototype: HTMLPortfolioTerminalElement;
        new (): HTMLPortfolioTerminalElement;
    };
    interface HTMLPortfolioTopbarElementEventMap {
        "cmdK": void;
        "cmdAction": { action: string };
    }
    interface HTMLPortfolioTopbarElement extends Components.PortfolioTopbar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPortfolioTopbarElementEventMap>(type: K, listener: (this: HTMLPortfolioTopbarElement, ev: PortfolioTopbarCustomEvent<HTMLPortfolioTopbarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPortfolioTopbarElementEventMap>(type: K, listener: (this: HTMLPortfolioTopbarElement, ev: PortfolioTopbarCustomEvent<HTMLPortfolioTopbarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPortfolioTopbarElement: {
        prototype: HTMLPortfolioTopbarElement;
        new (): HTMLPortfolioTopbarElement;
    };
    interface HTMLPortfolioTrajectoryElement extends Components.PortfolioTrajectory, HTMLStencilElement {
    }
    var HTMLPortfolioTrajectoryElement: {
        prototype: HTMLPortfolioTrajectoryElement;
        new (): HTMLPortfolioTrajectoryElement;
    };
    interface HTMLElementTagNameMap {
        "app-portfolio": HTMLAppPortfolioElement;
        "intro-button": HTMLIntroButtonElement;
        "my-taypage": HTMLMyTaypageElement;
        "portfolio-cmdk": HTMLPortfolioCmdkElement;
        "portfolio-communication": HTMLPortfolioCommunicationElement;
        "portfolio-contact": HTMLPortfolioContactElement;
        "portfolio-hero": HTMLPortfolioHeroElement;
        "portfolio-ledgb": HTMLPortfolioLedgbElement;
        "portfolio-manifesto": HTMLPortfolioManifestoElement;
        "portfolio-projects": HTMLPortfolioProjectsElement;
        "portfolio-sect-head": HTMLPortfolioSectHeadElement;
        "portfolio-stack": HTMLPortfolioStackElement;
        "portfolio-terminal": HTMLPortfolioTerminalElement;
        "portfolio-topbar": HTMLPortfolioTopbarElement;
        "portfolio-trajectory": HTMLPortfolioTrajectoryElement;
    }
}
declare namespace LocalJSX {
    interface AppPortfolio {
    }
    interface IntroButton {
        "onSetchangetext"?: () => void;
        "playButtonRef"?: (el: HTMLDivElement) => void;
    }
    interface MyTaypage {
    }
    interface PortfolioCmdk {
        /**
          * @default 'pt'
         */
        "locale"?: Lang;
        "onCmdAction"?: (event: PortfolioCmdkCustomEvent<{ action: string }>) => void;
        "onCmdClose"?: (event: PortfolioCmdkCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface PortfolioCommunication {
        /**
          * @default 'pt'
         */
        "locale"?: Lang;
    }
    interface PortfolioContact {
        /**
          * @default 'pt'
         */
        "locale"?: Lang;
        "onCopyEmail"?: (event: PortfolioContactCustomEvent<void>) => void;
    }
    interface PortfolioHero {
        /**
          * @default 'pt'
         */
        "locale"?: Lang;
    }
    interface PortfolioLedgb {
        /**
          * @default 'pt'
         */
        "locale"?: Lang;
    }
    interface PortfolioManifesto {
        /**
          * @default 'pt'
         */
        "locale"?: Lang;
    }
    interface PortfolioProjects {
        /**
          * @default 'pt'
         */
        "locale"?: Lang;
    }
    interface PortfolioSectHead {
        /**
          * @default ''
         */
        "num"?: string;
        /**
          * @default ''
         */
        "sub"?: string;
        /**
          * @default ''
         */
        "titleHtml"?: string;
    }
    interface PortfolioStack {
        /**
          * @default 'pt'
         */
        "locale"?: Lang;
    }
    interface PortfolioTerminal {
    }
    interface PortfolioTopbar {
        /**
          * @default 'pt'
         */
        "locale"?: Lang;
        "onCmdAction"?: (event: PortfolioTopbarCustomEvent<{ action: string }>) => void;
        "onCmdK"?: (event: PortfolioTopbarCustomEvent<void>) => void;
    }
    interface PortfolioTrajectory {
        /**
          * @default 'pt'
         */
        "locale"?: Lang;
    }

    interface PortfolioCmdkAttributes {
        "locale": Lang;
        "open": boolean;
    }
    interface PortfolioCommunicationAttributes {
        "locale": Lang;
    }
    interface PortfolioContactAttributes {
        "locale": Lang;
    }
    interface PortfolioHeroAttributes {
        "locale": Lang;
    }
    interface PortfolioLedgbAttributes {
        "locale": Lang;
    }
    interface PortfolioManifestoAttributes {
        "locale": Lang;
    }
    interface PortfolioProjectsAttributes {
        "locale": Lang;
    }
    interface PortfolioSectHeadAttributes {
        "num": string;
        "titleHtml": string;
        "sub": string;
    }
    interface PortfolioStackAttributes {
        "locale": Lang;
    }
    interface PortfolioTopbarAttributes {
        "locale": Lang;
    }
    interface PortfolioTrajectoryAttributes {
        "locale": Lang;
    }

    interface IntrinsicElements {
        "app-portfolio": AppPortfolio;
        "intro-button": IntroButton;
        "my-taypage": MyTaypage;
        "portfolio-cmdk": Omit<PortfolioCmdk, keyof PortfolioCmdkAttributes> & { [K in keyof PortfolioCmdk & keyof PortfolioCmdkAttributes]?: PortfolioCmdk[K] } & { [K in keyof PortfolioCmdk & keyof PortfolioCmdkAttributes as `attr:${K}`]?: PortfolioCmdkAttributes[K] } & { [K in keyof PortfolioCmdk & keyof PortfolioCmdkAttributes as `prop:${K}`]?: PortfolioCmdk[K] };
        "portfolio-communication": Omit<PortfolioCommunication, keyof PortfolioCommunicationAttributes> & { [K in keyof PortfolioCommunication & keyof PortfolioCommunicationAttributes]?: PortfolioCommunication[K] } & { [K in keyof PortfolioCommunication & keyof PortfolioCommunicationAttributes as `attr:${K}`]?: PortfolioCommunicationAttributes[K] } & { [K in keyof PortfolioCommunication & keyof PortfolioCommunicationAttributes as `prop:${K}`]?: PortfolioCommunication[K] };
        "portfolio-contact": Omit<PortfolioContact, keyof PortfolioContactAttributes> & { [K in keyof PortfolioContact & keyof PortfolioContactAttributes]?: PortfolioContact[K] } & { [K in keyof PortfolioContact & keyof PortfolioContactAttributes as `attr:${K}`]?: PortfolioContactAttributes[K] } & { [K in keyof PortfolioContact & keyof PortfolioContactAttributes as `prop:${K}`]?: PortfolioContact[K] };
        "portfolio-hero": Omit<PortfolioHero, keyof PortfolioHeroAttributes> & { [K in keyof PortfolioHero & keyof PortfolioHeroAttributes]?: PortfolioHero[K] } & { [K in keyof PortfolioHero & keyof PortfolioHeroAttributes as `attr:${K}`]?: PortfolioHeroAttributes[K] } & { [K in keyof PortfolioHero & keyof PortfolioHeroAttributes as `prop:${K}`]?: PortfolioHero[K] };
        "portfolio-ledgb": Omit<PortfolioLedgb, keyof PortfolioLedgbAttributes> & { [K in keyof PortfolioLedgb & keyof PortfolioLedgbAttributes]?: PortfolioLedgb[K] } & { [K in keyof PortfolioLedgb & keyof PortfolioLedgbAttributes as `attr:${K}`]?: PortfolioLedgbAttributes[K] } & { [K in keyof PortfolioLedgb & keyof PortfolioLedgbAttributes as `prop:${K}`]?: PortfolioLedgb[K] };
        "portfolio-manifesto": Omit<PortfolioManifesto, keyof PortfolioManifestoAttributes> & { [K in keyof PortfolioManifesto & keyof PortfolioManifestoAttributes]?: PortfolioManifesto[K] } & { [K in keyof PortfolioManifesto & keyof PortfolioManifestoAttributes as `attr:${K}`]?: PortfolioManifestoAttributes[K] } & { [K in keyof PortfolioManifesto & keyof PortfolioManifestoAttributes as `prop:${K}`]?: PortfolioManifesto[K] };
        "portfolio-projects": Omit<PortfolioProjects, keyof PortfolioProjectsAttributes> & { [K in keyof PortfolioProjects & keyof PortfolioProjectsAttributes]?: PortfolioProjects[K] } & { [K in keyof PortfolioProjects & keyof PortfolioProjectsAttributes as `attr:${K}`]?: PortfolioProjectsAttributes[K] } & { [K in keyof PortfolioProjects & keyof PortfolioProjectsAttributes as `prop:${K}`]?: PortfolioProjects[K] };
        "portfolio-sect-head": Omit<PortfolioSectHead, keyof PortfolioSectHeadAttributes> & { [K in keyof PortfolioSectHead & keyof PortfolioSectHeadAttributes]?: PortfolioSectHead[K] } & { [K in keyof PortfolioSectHead & keyof PortfolioSectHeadAttributes as `attr:${K}`]?: PortfolioSectHeadAttributes[K] } & { [K in keyof PortfolioSectHead & keyof PortfolioSectHeadAttributes as `prop:${K}`]?: PortfolioSectHead[K] };
        "portfolio-stack": Omit<PortfolioStack, keyof PortfolioStackAttributes> & { [K in keyof PortfolioStack & keyof PortfolioStackAttributes]?: PortfolioStack[K] } & { [K in keyof PortfolioStack & keyof PortfolioStackAttributes as `attr:${K}`]?: PortfolioStackAttributes[K] } & { [K in keyof PortfolioStack & keyof PortfolioStackAttributes as `prop:${K}`]?: PortfolioStack[K] };
        "portfolio-terminal": PortfolioTerminal;
        "portfolio-topbar": Omit<PortfolioTopbar, keyof PortfolioTopbarAttributes> & { [K in keyof PortfolioTopbar & keyof PortfolioTopbarAttributes]?: PortfolioTopbar[K] } & { [K in keyof PortfolioTopbar & keyof PortfolioTopbarAttributes as `attr:${K}`]?: PortfolioTopbarAttributes[K] } & { [K in keyof PortfolioTopbar & keyof PortfolioTopbarAttributes as `prop:${K}`]?: PortfolioTopbar[K] };
        "portfolio-trajectory": Omit<PortfolioTrajectory, keyof PortfolioTrajectoryAttributes> & { [K in keyof PortfolioTrajectory & keyof PortfolioTrajectoryAttributes]?: PortfolioTrajectory[K] } & { [K in keyof PortfolioTrajectory & keyof PortfolioTrajectoryAttributes as `attr:${K}`]?: PortfolioTrajectoryAttributes[K] } & { [K in keyof PortfolioTrajectory & keyof PortfolioTrajectoryAttributes as `prop:${K}`]?: PortfolioTrajectory[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-portfolio": LocalJSX.IntrinsicElements["app-portfolio"] & JSXBase.HTMLAttributes<HTMLAppPortfolioElement>;
            "intro-button": LocalJSX.IntrinsicElements["intro-button"] & JSXBase.HTMLAttributes<HTMLIntroButtonElement>;
            "my-taypage": LocalJSX.IntrinsicElements["my-taypage"] & JSXBase.HTMLAttributes<HTMLMyTaypageElement>;
            "portfolio-cmdk": LocalJSX.IntrinsicElements["portfolio-cmdk"] & JSXBase.HTMLAttributes<HTMLPortfolioCmdkElement>;
            "portfolio-communication": LocalJSX.IntrinsicElements["portfolio-communication"] & JSXBase.HTMLAttributes<HTMLPortfolioCommunicationElement>;
            "portfolio-contact": LocalJSX.IntrinsicElements["portfolio-contact"] & JSXBase.HTMLAttributes<HTMLPortfolioContactElement>;
            "portfolio-hero": LocalJSX.IntrinsicElements["portfolio-hero"] & JSXBase.HTMLAttributes<HTMLPortfolioHeroElement>;
            "portfolio-ledgb": LocalJSX.IntrinsicElements["portfolio-ledgb"] & JSXBase.HTMLAttributes<HTMLPortfolioLedgbElement>;
            "portfolio-manifesto": LocalJSX.IntrinsicElements["portfolio-manifesto"] & JSXBase.HTMLAttributes<HTMLPortfolioManifestoElement>;
            "portfolio-projects": LocalJSX.IntrinsicElements["portfolio-projects"] & JSXBase.HTMLAttributes<HTMLPortfolioProjectsElement>;
            "portfolio-sect-head": LocalJSX.IntrinsicElements["portfolio-sect-head"] & JSXBase.HTMLAttributes<HTMLPortfolioSectHeadElement>;
            "portfolio-stack": LocalJSX.IntrinsicElements["portfolio-stack"] & JSXBase.HTMLAttributes<HTMLPortfolioStackElement>;
            "portfolio-terminal": LocalJSX.IntrinsicElements["portfolio-terminal"] & JSXBase.HTMLAttributes<HTMLPortfolioTerminalElement>;
            "portfolio-topbar": LocalJSX.IntrinsicElements["portfolio-topbar"] & JSXBase.HTMLAttributes<HTMLPortfolioTopbarElement>;
            "portfolio-trajectory": LocalJSX.IntrinsicElements["portfolio-trajectory"] & JSXBase.HTMLAttributes<HTMLPortfolioTrajectoryElement>;
        }
    }
}
